#include<stdio.h>
void main()
{

 float a[10];
scanf("%f",&a[0]);
scanf("%f",&a[1]);
scanf("%f",&a[2]);
scanf("%f",&a[3]);
scanf("%f",&a[4]);
scanf("%f",&a[5]);
scanf("%f",&a[6]);
scanf("%f",&a[7]);
scanf("%f",&a[8]);
scanf("%f",&a[9]);

printf("%f",a[0]);
printf("%f",a[1]);
printf("%f",a[2]);
printf("%f",a[3]);
printf("%f",a[4]);
printf("%f",a[5]);
printf("%f",a[6]);
printf("%f",a[7]);
printf("%f",a[8]);
printf("%f",a[9]);



}